name=IntroSatLib
version=0.2.0
author=Dolgoarshinnykh Almaz
maintainer=Aleksey Gilenko
sentence=Library for educational satellite kit IntroSat
paragraph=
category=Device Control
url=https://github.com/Obu-IntroSat/IntroSatLib
architectures=stm32, avr, riscv
