#ifndef FSC_BT986_AT_COMMANDS_
#define FSC_BT986_AT_COMMANDS_


#define AT_HELP                     "AT+HELP\r\n"
#define AT_UART_TEST                "AT\r\n"
#define AT_REBOOT                   "AT+REBOOT\r\n"
#define AT_RESTORE                  "AT+RESTORE\r\n"
#define AT_BTEN                     "AT+BTEN\r\n"
#define AT_BTEN(p1)                 "AT+BTEN=" #p1 "\r\n"
#define AT_NAME                     "AT+NAME\r\n"
#define AT_NAME(p1)                 "AT+NAME=" #p1 "\r\n"
#define AT_NAME(p1, p2)             "AT+NAME=" #p1 "," #p2 "\r\n"
#define AT_LENAME                   "AT+LENAME\r\n"
#define AT_LENAME(p1)               "AT+LENAME=" #p1 "\r\n"
#define AT_LENAME(p1, p2)           "AT+LENAME=" #p1 "," #p2 "\r\n"
#define AT_PIN                      "AT+PIN\r\n"
#define AT_PIN(p1)                  "AT+PIN=" #p1 "\r\n"
#define AT_PLIST                    "AT+PLIST\r\n"
#define AT_PLIST(p1)                "AT+PLIST=" #p1 "\r\n"
#define AT_BAUD                     "AT+BAUD\r\n"
#define AT_BAUD(p1)                 "AT+BAUD=" #p1 "\r\n"
#define AT_LPM                      "AT+LPM\r\n"
#define AT_LPM(p1)                  "AT+LPM=" #p1 "\r\n"
#define AT_VER                      "AT+VER\r\n"
#define AT_ADDR                     "AT+ADDR\r\n"
#define AT_LEADDR                   "AT+LEADDR\r\n"
#define AT_COD                      "AT+COD\r\n"
#define AT_COD(p1)                  "AT+COD=" #p1 "\r\n"
#define AT_TPMODE                   "AT+TPMODE\r\n"
#define AT_TPMODE(p1)               "AT+TPMODE=" #p1 "\r\n"
#define AT_FLOWCTL                  "AT+FLOWCTL\r\n"
#define AT_FLOWCTL(p1)              "AT+FLOWCTL=" #p1 "\r\n"
#define AT_SSP                      "AT+SSP\r\n"
#define AT_SSP(p1)                  "AT+SSP=" #p1 "\r\n"
#define AT_MODE                     "AT+MODE\r\n"
#define AT_MODE(p1)                 "AT+MODE=" #p1 "\r\n"
#define AT_AUTOCONN                 "AT+AUTOCONN\r\n"
#define AT_AUTOCONN(p1)             "AT+AUTOCONN=" #p1 "\r\n"
#define AT_PIOCFG                   "AT+PIOCFG\r\n"
#define AT_PIOCFG(p1, p2)           "AT+PIOCFG=" #p1 "," #p2 "\r\n"
#define AT_DSCA                     "AT+DSCA\r\n"
#define AT_SCAN(p1)                 "AT+SCAN=" #p1 "\r\n"
#define AT_SCAN(p1, p2)             "AT+SCAN=" #p1 "," #p2 "\r\n"
#define AT_SCAN(p1, p2, p3)         "AT+SCAN=" #p1 "," #p2 "," #p3 "\r\n"
#define AT_SECURITY                 "AT+SECURITY\r\n"
#define AT_SECURITY(p1)             "AT+SECURITY=" #p1 "\r\n"
#define AT_TXPOWER                  "AT+TXPOWER\r\n"
#define AT_TXPOWER(p1)              "AT+TXPOWER=" #p1 "\r\n"
#define AT_UARTCFG                  "AT+UARTCFG\r\n"
#define AT_UARTCFG(p1)              "AT+UARTCFG=" #p1 "\r\n"
#define AT_LINKCFG                  "AT+LINKCFG\r\n"
#define AT_LINKCFG(p1)              "AT+LINKCFG=" #p1 "\r\n"
#define AT_RSSICFG                  "AT+RSSICFG\r\n"
#define AT_RSSICFG(p1, p2)          "AT+RSSICFG=" #p1 "," #p2 "\r\n"
#define AT_SPPSTAT                  "AT+SPPSTAT\r\n"
#define AT_SPPCFG                   "AT+SPPCFG\r\n"
#define AT_SPPCFG(p1)               "AT+SPPCFG=" #p1 "\r\n"
#define AT_SPPCONN                  "AT+SPPCONN\r\n"
#define AT_SPPCONN(p1)              "AT+SPPCONN=" #p1 "\r\n"
#define AT_SPPDISC                  "AT+SPPDISC\r\n"
#define AT_SPPSEND(p1, p2)          "AT+SPPSEND=" #p1 "," #p2 "\r\n"
#define AT_GATTSTAT                 "AT+GATTSTAT\r\n"
#define AT_ADVADDR                  "AT+ADVADDR\r\n"
#define AT_ADVADDR(p1)              "AT+ADVADDR=" #p1 "\r\n"
#define AT_IBEACON                  "AT+IBEACON\r\n"
#define AT_IBEACON(p1)              "AT+IBEACON=" #p1 "\r\n"
#define AT_ADVDATA                  "AT+ADVDATA\r\n"
#define AT_ADVDATA(p1)              "AT+ADVDATA=" #p1 "\r\n"
#define AT_ADBLE                    "AT+ADBLE\r\n"
#define AT_ADBLE(p1)                "AT+ADBLE=" #p1 "\r\n"
#define AT_UUIDCFG                  "AT+UUIDCFG\r\n"
#define AT_UUIDCFG(p1, p2, p3)      "AT+UUIDCFG=" #p1 "," #p2 "," #p3 "\r\n"
#define AT_GATTSEND(p1, p2)         "AT+GATTSEND=" #p1 "," #p2 "\r\n"
#define AT_LESTAT                   "AT+LESTAT\r\n"
#define AT_LECCONN                  "AT+LECCONN\r\n"
#define AT_LECCONN(p1)              "AT+LECCONN=" #p1 "\r\n"
#define AT_LECCONN(p1, p2)          "AT+LECCONN=" #p1 "," #p2 "\r\n"
#define AT_LECCONN(p1, p2, p3)      "AT+LECCONN=" #p1 "," #p2 "," #p3 "\r\n"
#define AT_LECCONN(p1, p2, p3, p4)  "AT+LECCONN=" #p1 "," #p2 "," #p3 "," #p4 "\r\n"
#define AT_LESEND(p1, p2)           "AT+LESEND=" #p1 "," #p2 "\r\n"
#define AT_HIDSTAT                  "AT+HIDSTAT\r\n"
#define AT_HIDCONN                  "AT+HIDCONN\r\n"
#define AT_HIDCONN(p1)              "AT+HIDCONN=" #p1 "\r\n"
#define AT_HIDDISC                  "AT+HIDDISC\r\n"
#define AT_HIDOSK                   "AT+HIDOSK\r\n"
#define AT_HIDMODE                  "AT+HIDMODE\r\n"
#define AT_HIDMODE(p1)              "AT+HIDMODE=" #p1 "\r\n"
#define AT_HIDDLY                   "AT+HIDDLY\r\n"
#define AT_HIDDLY(p1)               "AT+HIDDLY=" #p1 "\r\n"
#define AT_HIDSEND(p1, p2)          "AT+HIDSEND=" #p1 "," #p2 "\r\n"



#endif /* FSC_BT986_AT_COMMANDS_ */