name: Compile Examples on Linux

# See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/compile-examples-linux.yml"
      - "examples/**"
      - "src/**"
    branches: 
      - main
      - dev/actions
  pull_request:
    paths:
      - ".github/workflows/compile-examples-linux.yml"
      - "examples/**"
      - "src/**"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage caused by changes to external resources (libraries, platforms).
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fqbn:
          - STMicroelectronics:stm32:GenF1:pnum=BLUEPILL_F103C8
          - STMicroelectronics:stm32:GenH7:pnum=H750VB
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: STMicroelectronics:stm32
              source-url: https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json
          # sketch-paths: |
          #   - examples/Gyroscope/Base
          #   - examples/Acceleromter/*
          cli-compile-flags: |
            - --warnings="none"
